# Site settings
title: HCLib
email: zoran@rice.edu
description: > 
  "Habanero-C Library: A Compiler-Free Task-Parallel Library for C and C++"
baseurl: "/hclib" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  budimlic

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
